mail:
  host: smtp.gmail.com
  port: 587
  username: ${MAIL_USERNAME:alymaciel8@gmail.com}
  password: ${MAIL_PASSWORD:fulz dqaq tpsy mncv}

aws:
  region: ${AWS_REGION:us-east-1}
  accessKeyId: ${AWS_ACCESS_KEY_ID:AKIARSU7KYCVAEWLDB7E}
  secretKey: ${AWS_SECRET_ACCESS_KEY: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}
  ses:
    sender: ${AWS_SES_SENDER:alymaciel8@gmail.com}

email:
  provider: ${MAIL_PROVIDER:aws}

server:
  port: ${PORT:8080}
  servlet:
    context-path: "/v1"

# swagger-ui and api-docs custom path
springdoc:
  swagger-ui:
    path: "/swagger-ui"
  api-docs:
    path: "/api-docs"

