mail:
  host: smtp.gmail.com
  port: 587
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

aws:
  region: ${AWS_REGION}
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  ses:
    sender: ${AWS_SES_SENDER}

email:
  provider: ${MAIL_PROVIDER}

server:
  port: ${PORT:8080}  # Define a porta a partir da variável de ambiente PORT ou usa 8080 como fallback
  servlet:
    context-path: "/v1"

# swagger-ui and api-docs custom path
springdoc:
  swagger-ui:
    path: "/swagger-ui"
  api-docs:
    path: "/api-docs"

